### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by ngocthily** [ngocthily/Proofs-Line#3]
Heroku site: https://proofs-line.herokuapp.com/#/
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by mwmadsen67** [comment]
Everything seems to work well, but you still need to add styling. Also the demo login button should login the user, rather than just filling in the form.

**Comment by ngocthily** [comment]
- [ ] styling
- [ ] Smooth, bug-free navigation
- I fixed the log in demo and now it waits a moment before automatically logging in
- I added CSS, but will come back to fix the bugs I see

**Comment by mwmadsen67** [comment]
Awesome! The css looks great. 
Some small issues: 
- the password field has the letters show up. This can be fixed by changing the field type to password `<input type="password" ...`
-  the signup form gets spread out when the screen is bigger (my normal screen size), which messes up the styling. It looked normal again when I opened devtools. If the width of the form scales with screen size maybe adjust that to have a maxwidth?
- the errors should show up in red

You're free to work on the next MVP but make sure to address those changes eventually.

**Comment by mwmadsen67** [comment]
![Screen Shot 2020-05-01 at 1 34 20 PM](https://user-images.githubusercontent.com/45531900/80845335-ba5da300-8bbd-11ea-87a6-6226330ec3c4.png)

**Comment by ngocthily** [comment]
I fixed those 3 issues you mentioned. Let me know if there is any other issues you see that I should put down on my to-do list

**Comment by mwmadsen67** [comment]
Looks great!
